name: ssh
on:
  workflow_dispatch:
    inputs:
      sshPublicKey:
        description: 'SSH public key'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start ssh
        uses: mdelillo/ssh-server-action@v1.0.0
        with:
          ngrok-authtoken: "${{ secrets.NGROK_AUTHTOKEN }}"
          ssh-public-key: "${{ github.event.inputs.sshPublicKey }}"
